sources:
  - name: nytaxi
    database: de-zoomcamp-week4-487602 # Or name of your GCP project
    schema: nytaxi # Or name of your BigQuery dataset
    
    tables:
      - name: green_tripdata
      - name: yellow_tripdata